workflows:
  my-workflow:
    name: Club & Casa
    labels:
      - Dev

    instance_type: linux
    max_build_duration: 120
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "1.0.0"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - ...
    artifacts:
    publishing:
      email:
        recipients:
          - adilson.pina@clubecasadesign.com.br
      scripts:
        - echo 'Post-publish script'